# GitHub API configuration
github_api_base_url: "https://api.github.com"
github_api_token: ""

# File processing configuration
max_file_size: 104857600  # 100MB
supported_file_extensions:
  - .py
  - .js
  - .java
  - .c
  - .cpp
  - .md
  - .txt
  - .html
  - .css
  - .json
  - .yaml
  - .yml
  - .h
  - .rb
  - .ts
  - .php
  - .cs
  - .swift
  - .go
  - .rs
  - .sh
  - .bat
  - .pl
  - .r
  - .m
  - .lua
  - .kt
  - .dart
  - .asm
  - .sql
  - .vb
  - .vbs
  - .ps1
  - .groovy
  - .scala
  - .clj
  - .erl
  - .ex
  - .fs
  - .hs

# Directories and files to ignore
ignore_dirs:
  - .git
  - node_modules
  - venv
  - __pycache__
  - .idea
  - .vscode

ignore_files:
  - .gitignore
  - .DS_Store
  - Thumbs.db
  - .env

# Output configuration
supported_output_formats:
  - markdown
  - json
  - text
  - split
default_output_format: markdown

# Split format prompt templates
split_format_prompts:
  initial: "I am going to provide you with the file tree and code of a repository. Please do not respond until I say {final}"
  repo_name: "The repository name is {repo_name}"
  file_tree: "Here is the file tree of the repository:"
  file_content: "Here is the code for the file at `{file_path}`"
  final: "That's all the files."
  conclusion: "All {file_count} files from the repository have been provided."

# Repository processing configuration
max_files_to_process: 100

# Prompt generation configuration
max_prompt_length: 100000000
include_file_metadata: true